# Generated by Django 3.1.4 on 2021-09-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='type',
            new_name='variation',
        ),
    ]
