# Generated by Django 3.1.4 on 2021-09-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210902_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='variation',
            new_name='type',
        ),
    ]
