# Generated by Django 3.1.4 on 2021-09-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210902_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='type',
            new_name='variation',
        ),
    ]
