# Generated by Django 3.1.4 on 2021-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210902_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='variations',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
