# Generated by Django 3.1.4 on 2021-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
